// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sequencing/sequencing.proto

package sequencing

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/gogoproto/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SubmitRollupTransactionRequest ...
type SubmitRollupTransactionRequest struct {
	// the unhashed rollup id
	RollupId []byte `protobuf:"bytes,1,opt,name=rollup_id,json=rollupId,proto3" json:"rollup_id,omitempty"`
	// the raw data bytes of the rollup transaction
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *SubmitRollupTransactionRequest) Reset()         { *m = SubmitRollupTransactionRequest{} }
func (m *SubmitRollupTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitRollupTransactionRequest) ProtoMessage()    {}
func (*SubmitRollupTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b389fdbc59f03c95, []int{0}
}
func (m *SubmitRollupTransactionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitRollupTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitRollupTransactionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitRollupTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitRollupTransactionRequest.Merge(m, src)
}
func (m *SubmitRollupTransactionRequest) XXX_Size() int {
	return m.Size()
}
func (m *SubmitRollupTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitRollupTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitRollupTransactionRequest proto.InternalMessageInfo

func (m *SubmitRollupTransactionRequest) GetRollupId() []byte {
	if m != nil {
		return m.RollupId
	}
	return nil
}

func (m *SubmitRollupTransactionRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// SubmitRollupTransactionResponse ...
type SubmitRollupTransactionResponse struct {
}

func (m *SubmitRollupTransactionResponse) Reset()         { *m = SubmitRollupTransactionResponse{} }
func (m *SubmitRollupTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitRollupTransactionResponse) ProtoMessage()    {}
func (*SubmitRollupTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b389fdbc59f03c95, []int{1}
}
func (m *SubmitRollupTransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitRollupTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitRollupTransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitRollupTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitRollupTransactionResponse.Merge(m, src)
}
func (m *SubmitRollupTransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *SubmitRollupTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitRollupTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitRollupTransactionResponse proto.InternalMessageInfo

// GetNextBatchRequest ...
type GetNextBatchRequest struct {
	// the unhashed rollup id
	RollupId []byte `protobuf:"bytes,1,opt,name=rollup_id,json=rollupId,proto3" json:"rollup_id,omitempty"`
	// Merkle tree hash of the last batch
	LastBatchHash []byte `protobuf:"bytes,2,opt,name=last_batch_hash,json=lastBatchHash,proto3" json:"last_batch_hash,omitempty"`
	// maximum bytes that execution client can support per block
	MaxBytes uint64 `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
}

func (m *GetNextBatchRequest) Reset()         { *m = GetNextBatchRequest{} }
func (m *GetNextBatchRequest) String() string { return proto.CompactTextString(m) }
func (*GetNextBatchRequest) ProtoMessage()    {}
func (*GetNextBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b389fdbc59f03c95, []int{2}
}
func (m *GetNextBatchRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetNextBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetNextBatchRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetNextBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextBatchRequest.Merge(m, src)
}
func (m *GetNextBatchRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetNextBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextBatchRequest proto.InternalMessageInfo

func (m *GetNextBatchRequest) GetRollupId() []byte {
	if m != nil {
		return m.RollupId
	}
	return nil
}

func (m *GetNextBatchRequest) GetLastBatchHash() []byte {
	if m != nil {
		return m.LastBatchHash
	}
	return nil
}

func (m *GetNextBatchRequest) GetMaxBytes() uint64 {
	if m != nil {
		return m.MaxBytes
	}
	return 0
}

// GetNextBatchResponse ...
type GetNextBatchResponse struct {
	Batch     *Batch           `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	Timestamp *types.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *GetNextBatchResponse) Reset()         { *m = GetNextBatchResponse{} }
func (m *GetNextBatchResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextBatchResponse) ProtoMessage()    {}
func (*GetNextBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b389fdbc59f03c95, []int{3}
}
func (m *GetNextBatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetNextBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetNextBatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetNextBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextBatchResponse.Merge(m, src)
}
func (m *GetNextBatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetNextBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextBatchResponse proto.InternalMessageInfo

func (m *GetNextBatchResponse) GetBatch() *Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

func (m *GetNextBatchResponse) GetTimestamp() *types.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// Batch holds a list of transactions
type Batch struct {
	Transactions [][]byte `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_b389fdbc59f03c95, []int{4}
}
func (m *Batch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return m.Size()
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// VerifyBatchRequest ...
type VerifyBatchRequest struct {
	// the unhashed rollup id
	RollupId []byte `protobuf:"bytes,1,opt,name=rollup_id,json=rollupId,proto3" json:"rollup_id,omitempty"`
	// Merkle tree hash of the batch
	BatchHash []byte `protobuf:"bytes,2,opt,name=batch_hash,json=batchHash,proto3" json:"batch_hash,omitempty"`
}

func (m *VerifyBatchRequest) Reset()         { *m = VerifyBatchRequest{} }
func (m *VerifyBatchRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyBatchRequest) ProtoMessage()    {}
func (*VerifyBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b389fdbc59f03c95, []int{5}
}
func (m *VerifyBatchRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifyBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifyBatchRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifyBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyBatchRequest.Merge(m, src)
}
func (m *VerifyBatchRequest) XXX_Size() int {
	return m.Size()
}
func (m *VerifyBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyBatchRequest proto.InternalMessageInfo

func (m *VerifyBatchRequest) GetRollupId() []byte {
	if m != nil {
		return m.RollupId
	}
	return nil
}

func (m *VerifyBatchRequest) GetBatchHash() []byte {
	if m != nil {
		return m.BatchHash
	}
	return nil
}

// VerifyBatchResponse
type VerifyBatchResponse struct {
	// status indicates the verification results
	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *VerifyBatchResponse) Reset()         { *m = VerifyBatchResponse{} }
func (m *VerifyBatchResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyBatchResponse) ProtoMessage()    {}
func (*VerifyBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b389fdbc59f03c95, []int{6}
}
func (m *VerifyBatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifyBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifyBatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifyBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyBatchResponse.Merge(m, src)
}
func (m *VerifyBatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *VerifyBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyBatchResponse proto.InternalMessageInfo

func (m *VerifyBatchResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*SubmitRollupTransactionRequest)(nil), "sequencing.SubmitRollupTransactionRequest")
	proto.RegisterType((*SubmitRollupTransactionResponse)(nil), "sequencing.SubmitRollupTransactionResponse")
	proto.RegisterType((*GetNextBatchRequest)(nil), "sequencing.GetNextBatchRequest")
	proto.RegisterType((*GetNextBatchResponse)(nil), "sequencing.GetNextBatchResponse")
	proto.RegisterType((*Batch)(nil), "sequencing.Batch")
	proto.RegisterType((*VerifyBatchRequest)(nil), "sequencing.VerifyBatchRequest")
	proto.RegisterType((*VerifyBatchResponse)(nil), "sequencing.VerifyBatchResponse")
}

func init() { proto.RegisterFile("sequencing/sequencing.proto", fileDescriptor_b389fdbc59f03c95) }

var fileDescriptor_b389fdbc59f03c95 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x8f, 0xd2, 0x40,
	0x14, 0xc7, 0x19, 0xf7, 0x47, 0xe0, 0xc1, 0xba, 0x71, 0xd6, 0x68, 0xd3, 0x8d, 0x03, 0xce, 0x41,
	0x89, 0x1b, 0x4b, 0x82, 0x17, 0xcf, 0x5c, 0x74, 0x2f, 0xba, 0x96, 0x8d, 0x57, 0x32, 0x85, 0x01,
	0x9a, 0xf4, 0x97, 0x9d, 0xd7, 0x08, 0xff, 0x80, 0x67, 0xff, 0x2c, 0x8f, 0x7b, 0xf4, 0x68, 0xe0,
	0x1f, 0x31, 0x9d, 0xb6, 0xb4, 0x04, 0x6b, 0xb8, 0xcd, 0xbc, 0xf7, 0xed, 0xf7, 0x3b, 0xfd, 0xbc,
	0x07, 0xd7, 0x4a, 0x7e, 0x4b, 0x64, 0x30, 0x75, 0x83, 0xc5, 0xa0, 0x3c, 0x5a, 0x51, 0x1c, 0x62,
	0x48, 0xa1, 0xac, 0x98, 0xdd, 0x45, 0x18, 0x2e, 0x3c, 0x39, 0xd0, 0x1d, 0x27, 0x99, 0x0f, 0xd0,
	0xf5, 0xa5, 0x42, 0xe1, 0x47, 0x99, 0x98, 0x7f, 0x01, 0x36, 0x4e, 0x1c, 0xdf, 0x45, 0x3b, 0xf4,
	0xbc, 0x24, 0xba, 0x8f, 0x45, 0xa0, 0xc4, 0x14, 0xdd, 0x30, 0xb0, 0x53, 0x17, 0x85, 0xf4, 0x1a,
	0x5a, 0xb1, 0xee, 0x4d, 0xdc, 0x99, 0x41, 0x7a, 0xa4, 0xdf, 0xb1, 0x9b, 0x59, 0xe1, 0x76, 0x46,
	0x29, 0x9c, 0xce, 0x04, 0x0a, 0xe3, 0x91, 0xae, 0xeb, 0x33, 0x7f, 0x09, 0xdd, 0x5a, 0x4b, 0x15,
	0x85, 0x81, 0x92, 0xfc, 0x3b, 0x5c, 0x7d, 0x90, 0xf8, 0x49, 0xae, 0x70, 0x24, 0x70, 0xba, 0x3c,
	0x2a, 0xea, 0x15, 0x5c, 0x7a, 0x42, 0xe1, 0xc4, 0x49, 0xbf, 0x98, 0x2c, 0x85, 0x5a, 0xe6, 0xa9,
	0x17, 0x69, 0x59, 0xfb, 0x7c, 0x14, 0x6a, 0x99, 0x9a, 0xf8, 0x62, 0x35, 0x71, 0xd6, 0x28, 0x95,
	0x71, 0xd2, 0x23, 0xfd, 0x53, 0xbb, 0xe9, 0x8b, 0xd5, 0x28, 0xbd, 0xf3, 0x35, 0x3c, 0xdd, 0x0f,
	0xce, 0x1e, 0x44, 0x5f, 0xc3, 0x99, 0xf6, 0xd5, 0xa9, 0xed, 0xe1, 0x13, 0xab, 0x42, 0x35, 0x53,
	0x66, 0x7d, 0xfa, 0x1e, 0x5a, 0x3b, 0x84, 0x3a, 0xbf, 0x3d, 0x34, 0xad, 0x0c, 0xb2, 0x55, 0x40,
	0xb6, 0xee, 0x0b, 0x85, 0x5d, 0x8a, 0xf9, 0x0d, 0x9c, 0x69, 0x27, 0xca, 0xa1, 0x83, 0x25, 0x13,
	0x65, 0x90, 0xde, 0x49, 0xbf, 0x63, 0xef, 0xd5, 0xf8, 0x1d, 0xd0, 0xaf, 0x32, 0x76, 0xe7, 0xeb,
	0xe3, 0xf9, 0xbc, 0x00, 0x38, 0x40, 0xd3, 0x72, 0x0a, 0x2c, 0xfc, 0x2d, 0x5c, 0xed, 0x39, 0xe6,
	0x3f, 0xfe, 0x0c, 0xce, 0x15, 0x0a, 0x4c, 0x94, 0xf6, 0x6b, 0xda, 0xf9, 0x6d, 0xf8, 0x83, 0xc0,
	0xe3, 0x71, 0xc6, 0x40, 0xc6, 0xb7, 0x41, 0x94, 0x20, 0x45, 0x78, 0x5e, 0x33, 0x57, 0xfa, 0xa6,
	0xca, 0xeb, 0xff, 0xfb, 0x64, 0xde, 0x1c, 0xa5, 0xcd, 0x17, 0xa5, 0x31, 0x9c, 0xc3, 0xe5, 0xee,
	0x1d, 0x9f, 0x13, 0x4c, 0x1f, 0x32, 0x86, 0x4e, 0x75, 0x88, 0xb4, 0x5b, 0x75, 0xfc, 0xc7, 0x5e,
	0x99, 0xbd, 0x7a, 0xc1, 0x2e, 0x47, 0xc0, 0x85, 0x2e, 0x69, 0x48, 0xae, 0x8c, 0xe9, 0x1d, 0xb4,
	0x2b, 0xc0, 0x28, 0xab, 0x7a, 0x1c, 0xce, 0xc6, 0xec, 0xd6, 0xf6, 0x8b, 0x88, 0x91, 0xf1, 0x6b,
	0xc3, 0xc8, 0xc3, 0x86, 0x91, 0x3f, 0x1b, 0x46, 0x7e, 0x6e, 0x59, 0xe3, 0x61, 0xcb, 0x1a, 0xbf,
	0xb7, 0xac, 0xe1, 0x9c, 0xeb, 0xd5, 0x79, 0xf7, 0x37, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xd3, 0x53,
	0x7b, 0xd8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SequencerInputClient is the client API for SequencerInput service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SequencerInputClient interface {
	// SubmitRollupTransaction ...
	SubmitRollupTransaction(ctx context.Context, in *SubmitRollupTransactionRequest, opts ...grpc.CallOption) (*SubmitRollupTransactionResponse, error)
}

type sequencerInputClient struct {
	cc grpc1.ClientConn
}

func NewSequencerInputClient(cc grpc1.ClientConn) SequencerInputClient {
	return &sequencerInputClient{cc}
}

func (c *sequencerInputClient) SubmitRollupTransaction(ctx context.Context, in *SubmitRollupTransactionRequest, opts ...grpc.CallOption) (*SubmitRollupTransactionResponse, error) {
	out := new(SubmitRollupTransactionResponse)
	err := c.cc.Invoke(ctx, "/sequencing.SequencerInput/SubmitRollupTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SequencerInputServer is the server API for SequencerInput service.
type SequencerInputServer interface {
	// SubmitRollupTransaction ...
	SubmitRollupTransaction(context.Context, *SubmitRollupTransactionRequest) (*SubmitRollupTransactionResponse, error)
}

// UnimplementedSequencerInputServer can be embedded to have forward compatible implementations.
type UnimplementedSequencerInputServer struct {
}

func (*UnimplementedSequencerInputServer) SubmitRollupTransaction(ctx context.Context, req *SubmitRollupTransactionRequest) (*SubmitRollupTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRollupTransaction not implemented")
}

func RegisterSequencerInputServer(s grpc1.Server, srv SequencerInputServer) {
	s.RegisterService(&_SequencerInput_serviceDesc, srv)
}

func _SequencerInput_SubmitRollupTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRollupTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequencerInputServer).SubmitRollupTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencing.SequencerInput/SubmitRollupTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequencerInputServer).SubmitRollupTransaction(ctx, req.(*SubmitRollupTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var SequencerInput_serviceDesc = _SequencerInput_serviceDesc
var _SequencerInput_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sequencing.SequencerInput",
	HandlerType: (*SequencerInputServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitRollupTransaction",
			Handler:    _SequencerInput_SubmitRollupTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sequencing/sequencing.proto",
}

// SequencerOutputClient is the client API for SequencerOutput service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SequencerOutputClient interface {
	// GetNextBatch ...
	GetNextBatch(ctx context.Context, in *GetNextBatchRequest, opts ...grpc.CallOption) (*GetNextBatchResponse, error)
}

type sequencerOutputClient struct {
	cc grpc1.ClientConn
}

func NewSequencerOutputClient(cc grpc1.ClientConn) SequencerOutputClient {
	return &sequencerOutputClient{cc}
}

func (c *sequencerOutputClient) GetNextBatch(ctx context.Context, in *GetNextBatchRequest, opts ...grpc.CallOption) (*GetNextBatchResponse, error) {
	out := new(GetNextBatchResponse)
	err := c.cc.Invoke(ctx, "/sequencing.SequencerOutput/GetNextBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SequencerOutputServer is the server API for SequencerOutput service.
type SequencerOutputServer interface {
	// GetNextBatch ...
	GetNextBatch(context.Context, *GetNextBatchRequest) (*GetNextBatchResponse, error)
}

// UnimplementedSequencerOutputServer can be embedded to have forward compatible implementations.
type UnimplementedSequencerOutputServer struct {
}

func (*UnimplementedSequencerOutputServer) GetNextBatch(ctx context.Context, req *GetNextBatchRequest) (*GetNextBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextBatch not implemented")
}

func RegisterSequencerOutputServer(s grpc1.Server, srv SequencerOutputServer) {
	s.RegisterService(&_SequencerOutput_serviceDesc, srv)
}

func _SequencerOutput_GetNextBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequencerOutputServer).GetNextBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencing.SequencerOutput/GetNextBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequencerOutputServer).GetNextBatch(ctx, req.(*GetNextBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var SequencerOutput_serviceDesc = _SequencerOutput_serviceDesc
var _SequencerOutput_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sequencing.SequencerOutput",
	HandlerType: (*SequencerOutputServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNextBatch",
			Handler:    _SequencerOutput_GetNextBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sequencing/sequencing.proto",
}

// BatchVerifierClient is the client API for BatchVerifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BatchVerifierClient interface {
	// VerifyBatch ...
	VerifyBatch(ctx context.Context, in *VerifyBatchRequest, opts ...grpc.CallOption) (*VerifyBatchResponse, error)
}

type batchVerifierClient struct {
	cc grpc1.ClientConn
}

func NewBatchVerifierClient(cc grpc1.ClientConn) BatchVerifierClient {
	return &batchVerifierClient{cc}
}

func (c *batchVerifierClient) VerifyBatch(ctx context.Context, in *VerifyBatchRequest, opts ...grpc.CallOption) (*VerifyBatchResponse, error) {
	out := new(VerifyBatchResponse)
	err := c.cc.Invoke(ctx, "/sequencing.BatchVerifier/VerifyBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BatchVerifierServer is the server API for BatchVerifier service.
type BatchVerifierServer interface {
	// VerifyBatch ...
	VerifyBatch(context.Context, *VerifyBatchRequest) (*VerifyBatchResponse, error)
}

// UnimplementedBatchVerifierServer can be embedded to have forward compatible implementations.
type UnimplementedBatchVerifierServer struct {
}

func (*UnimplementedBatchVerifierServer) VerifyBatch(ctx context.Context, req *VerifyBatchRequest) (*VerifyBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyBatch not implemented")
}

func RegisterBatchVerifierServer(s grpc1.Server, srv BatchVerifierServer) {
	s.RegisterService(&_BatchVerifier_serviceDesc, srv)
}

func _BatchVerifier_VerifyBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchVerifierServer).VerifyBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencing.BatchVerifier/VerifyBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchVerifierServer).VerifyBatch(ctx, req.(*VerifyBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var BatchVerifier_serviceDesc = _BatchVerifier_serviceDesc
var _BatchVerifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sequencing.BatchVerifier",
	HandlerType: (*BatchVerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyBatch",
			Handler:    _BatchVerifier_VerifyBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sequencing/sequencing.proto",
}

func (m *SubmitRollupTransactionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitRollupTransactionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitRollupTransactionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintSequencing(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RollupId) > 0 {
		i -= len(m.RollupId)
		copy(dAtA[i:], m.RollupId)
		i = encodeVarintSequencing(dAtA, i, uint64(len(m.RollupId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubmitRollupTransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitRollupTransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitRollupTransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetNextBatchRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetNextBatchRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetNextBatchRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxBytes != 0 {
		i = encodeVarintSequencing(dAtA, i, uint64(m.MaxBytes))
		i--
		dAtA[i] = 0x18
	}
	if len(m.LastBatchHash) > 0 {
		i -= len(m.LastBatchHash)
		copy(dAtA[i:], m.LastBatchHash)
		i = encodeVarintSequencing(dAtA, i, uint64(len(m.LastBatchHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RollupId) > 0 {
		i -= len(m.RollupId)
		copy(dAtA[i:], m.RollupId)
		i = encodeVarintSequencing(dAtA, i, uint64(len(m.RollupId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetNextBatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetNextBatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetNextBatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != nil {
		{
			size, err := m.Timestamp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSequencing(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Batch != nil {
		{
			size, err := m.Batch.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSequencing(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Batch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Batch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Batch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for iNdEx := len(m.Transactions) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Transactions[iNdEx])
			copy(dAtA[i:], m.Transactions[iNdEx])
			i = encodeVarintSequencing(dAtA, i, uint64(len(m.Transactions[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *VerifyBatchRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifyBatchRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerifyBatchRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BatchHash) > 0 {
		i -= len(m.BatchHash)
		copy(dAtA[i:], m.BatchHash)
		i = encodeVarintSequencing(dAtA, i, uint64(len(m.BatchHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RollupId) > 0 {
		i -= len(m.RollupId)
		copy(dAtA[i:], m.RollupId)
		i = encodeVarintSequencing(dAtA, i, uint64(len(m.RollupId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VerifyBatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifyBatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerifyBatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status {
		i--
		if m.Status {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSequencing(dAtA []byte, offset int, v uint64) int {
	offset -= sovSequencing(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SubmitRollupTransactionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollupId)
	if l > 0 {
		n += 1 + l + sovSequencing(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovSequencing(uint64(l))
	}
	return n
}

func (m *SubmitRollupTransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetNextBatchRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollupId)
	if l > 0 {
		n += 1 + l + sovSequencing(uint64(l))
	}
	l = len(m.LastBatchHash)
	if l > 0 {
		n += 1 + l + sovSequencing(uint64(l))
	}
	if m.MaxBytes != 0 {
		n += 1 + sovSequencing(uint64(m.MaxBytes))
	}
	return n
}

func (m *GetNextBatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Batch != nil {
		l = m.Batch.Size()
		n += 1 + l + sovSequencing(uint64(l))
	}
	if m.Timestamp != nil {
		l = m.Timestamp.Size()
		n += 1 + l + sovSequencing(uint64(l))
	}
	return n
}

func (m *Batch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for _, b := range m.Transactions {
			l = len(b)
			n += 1 + l + sovSequencing(uint64(l))
		}
	}
	return n
}

func (m *VerifyBatchRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollupId)
	if l > 0 {
		n += 1 + l + sovSequencing(uint64(l))
	}
	l = len(m.BatchHash)
	if l > 0 {
		n += 1 + l + sovSequencing(uint64(l))
	}
	return n
}

func (m *VerifyBatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status {
		n += 2
	}
	return n
}

func sovSequencing(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSequencing(x uint64) (n int) {
	return sovSequencing(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SubmitRollupTransactionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSequencing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitRollupTransactionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitRollupTransactionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSequencing
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupId = append(m.RollupId[:0], dAtA[iNdEx:postIndex]...)
			if m.RollupId == nil {
				m.RollupId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSequencing
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSequencing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSequencing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitRollupTransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSequencing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitRollupTransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitRollupTransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipSequencing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSequencing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetNextBatchRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSequencing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetNextBatchRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetNextBatchRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSequencing
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupId = append(m.RollupId[:0], dAtA[iNdEx:postIndex]...)
			if m.RollupId == nil {
				m.RollupId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastBatchHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSequencing
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastBatchHash = append(m.LastBatchHash[:0], dAtA[iNdEx:postIndex]...)
			if m.LastBatchHash == nil {
				m.LastBatchHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBytes", wireType)
			}
			m.MaxBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBytes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSequencing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSequencing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetNextBatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSequencing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetNextBatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetNextBatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Batch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSequencing
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSequencing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Batch == nil {
				m.Batch = &Batch{}
			}
			if err := m.Batch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSequencing
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSequencing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Timestamp == nil {
				m.Timestamp = &types.Timestamp{}
			}
			if err := m.Timestamp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSequencing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSequencing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Batch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSequencing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Batch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Batch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transactions", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSequencing
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transactions = append(m.Transactions, make([]byte, postIndex-iNdEx))
			copy(m.Transactions[len(m.Transactions)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSequencing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSequencing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerifyBatchRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSequencing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifyBatchRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifyBatchRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSequencing
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupId = append(m.RollupId[:0], dAtA[iNdEx:postIndex]...)
			if m.RollupId == nil {
				m.RollupId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSequencing
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchHash = append(m.BatchHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BatchHash == nil {
				m.BatchHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSequencing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSequencing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerifyBatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSequencing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifyBatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifyBatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Status = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipSequencing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSequencing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSequencing(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSequencing
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSequencing
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSequencing
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSequencing
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSequencing
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSequencing        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSequencing          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSequencing = fmt.Errorf("proto: unexpected end of group")
)
