name: Docker Build & Publish

# Trigger on all push events, new semantic version tags, and all PRs
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

jobs:
  go-sequencing-docker:
    permissions:
      contents: write
      packages: write
    uses: rollkit/.github/.github/workflows/reusable_dockerfile_pipeline.yml@v0.5.0 # yamllint disable-line rule:line-length
    with:
      dockerfile: Dockerfile
    secrets: inherit
